version: 1.0.2.{build}
branches:
  only:
  - master
image: Visual Studio 2017
build_script:
- cmd: dotnet build src\GranSteL.Helpers.sln -c Release
test_script:
- cmd: dotnet test "src\GranSteL.Helpers.Redis.Tests" -c Release